### ISSUE TITLE
Syntax is wrong

### ISSUE THREAD

**Issue by mattlawiscool** [udacity/OOJS-screencasts#1]
Say hello function should be: 
function sayHello(message) {
  console.log(`${message}, ${this.name}`);
}

not this.message

**Comment by bobdeei** [comment]
I agree with @mattlawiscool. The syntax inside the `console.log` is wrong. There shouldn't be any `this.` before `message`. Otherwise, the result will be `undefined, Bailey` since the object `cat` does not have any `message` property.

The code is not consistent with the video shown in lesson 3.

**Comment by hotboy01** [comment]
i think i agree with @mattlawiscool too

**Comment by hbkwong** [comment]
This has since been updated. Thanks everyone!
